controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user:
    resource: ../src/Controller/User
    type: attribute
    prefix: '/u/'

consultant:
    resource: ../src/Controller/Consultant
    type: attribute
    prefix: 'consultant'

admin:
    resource: ../src/Controller/Admin
    type: attribute
    prefix: '_admin'
