controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


myflix:
    resource: ../src/Controller/Myflix
    type: attribute
    prefix: '/myflix'